### ISSUE TITLE
Program exits with status 1

### ISSUE THREAD

**Issue by friederbluemle** [mafik/logitech-g600-linux#1]
I followed the instructions given under "Usage", but when I start `./g600` it simply exits immediately with code `1`. Is there a way to enable a verbose mode to see what's wrong?

**Comment by mafik** [comment]
g600.cpp tried a hardcoded path and crashed when it didn't exist. It was wrong because the path was specific to my device. I've fixed it and added some more verbose error messages.

**Comment by friederbluemle** [comment]
@mafik Great thanks!! I actually edited the hard-coded path to match my machine-specific path before compiling the file. Let me check again at my home computer tonight, and I'll report back here.

**Comment by friederbluemle** [comment]
Awesome!! It works! Thanks @mafik :+1:
